### ISSUE TITLE
rocketseat-advanced not found.

### ISSUE THREAD

**Issue by avitorio** [Rocketseat/react-native-template-rocketseat-advanced#6]
Oi,
Tentei instalar o template usando:
npx react-native init MyProject --template rocketseat-advanced

E recebi esse erro:

**error An unexpected error occurred: "https://registry.yarnpkg.com/rocketseat-advanced: Not found".**

Alguma sugestão?

**Comment by jpedroschmitz** [comment]
Fala @avitorio, 

Eu executei o comando `npx react-native init MyProject --template rocketseat-advanced` e não tive nenhum problema. Recomendo você dar uma verificada se está com tudo instalado corretamente.

**Comment by avitorio** [comment]
@jpedroschmitz Obrigado por testar. Eu tive que instalar o react-native globalmente pra conseguir rodar. Através do npx tava bugando. Dizia que o 'yarn add rocketseat-advanced' não funcionava pq o package rocketseat-advanced não existe. Talvez ele devesse rodar o comando 'yarn add react-native-template-rocketseat-advanced'... não entendo como esses packages/templates funcionam. Só tentando adicionar umas infos aqui pra que se alguem cruzar com esse erro no futuro tenha essa referência. Abraço!

**Comment by jpedroschmitz** [comment]
Então, o yarn não estava bugado nesse caso, por que o pacote `rocketseat-advanced` não existe mesmo. Você tentou rodar o comando `yarn add rocketseat-advanced`, e o correto, para criar o projeto é `react-native init AwesomeExample --template rocketseat-advanced`. Você tem que iniciar o projeto normal e passar a flag template com o `rocketseat-advanced`.

**Comment by avitorio** [comment]
Na verdade eu não tentei rodar o comando yarn add rocketseat-advanced
diretamente, o log do erro dizia que o npx react-native init AwesomeExample
--template rocketseat-advanced que tentou executa-lo. Bom, de qualquer
maneira ta resolvido instalando o react-native cli globalmente. Valeu!

**Comment by WeslleyNasRocha** [comment]
Então eu estou com esse problema, estou com a versão `@react-native-community/cli@2.9.0` instalada globalmente mas mesmo assim não funciona
```sh
~/development took 6s 
❯ react-native init MyProject --template rocketseat-advanced
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn Once Write Anywhere                

✖ Downloading template
error Error: Command failed: yarn add rocketseat-advanced
error An unexpected error occurred: "https://registry.yarnpkg.com/rocketseat-advanced: Not found".
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
info If you think this is a bug, please open a bug report with the information provided in "/private/var/folders/rd/k18lc0y91tdd918xw0slyfgm0000gn/T/rncli-init-template-1vebzk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
