### ISSUE TITLE
Erro ao usar --template

### ISSUE THREAD

**Issue by igortice** [Rocketseat/react-native-template-rocketseat-advanced#9]
ao executar o seguinte comando no mac:
npx react-native init AwesomeExample --template rocketseat-advanced
o erro abaixo aparece
![Captura de Tela 2020-01-11 às 13 29 51](https://user-images.githubusercontent.com/1306646/72207273-7ad84300-3476-11ea-8528-3435f9f127ff.png)

**Comment by saade** [comment]
Conseguiu corrigir mano?
